-- Sequence: public."oairunresult_ID_seq"

-- DROP SEQUENCE IF EXISTS public."oairunresult_ID_seq";

CREATE SEQUENCE IF NOT EXISTS public."oairunresult_ID_seq"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE public."oairunresult_ID_seq"
  OWNER TO "reportingDB";


-- Table: public."OAIRunResult"

-- DROP TABLE IF EXISTS public."OAIRunResult";

CREATE TABLE IF NOT EXISTS public."OAIRunResult"
(
  "ID" integer NOT NULL DEFAULT nextval('"oairunresult_ID_seq"'::regclass),
  "timestampOfRun" timestamp with time zone NOT NULL, -- the timestamp this run was started, generated locally
  "responseDate" timestamp with time zone NOT NULL, -- the responseDate from the OAI response, generated by remote server
  "resumptionToken" character varying(256), -- the resumption token in case there is any
  "resumptionTokenExpirationDate" timestamp with time zone, -- the resumption token's optional expiration date
  "nextFromTimestamp" timestamp with time zone, -- the value of the 'from' parameter to be used in the next GET request not containing a resumptionToken.
  CONSTRAINT "ID" PRIMARY KEY ("ID")
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public."OAIRunResult"
  OWNER TO "reportingDB";
COMMENT ON COLUMN public."OAIRunResult"."timestampOfRun" IS 'the timestamp this run was started, generated locally';
COMMENT ON COLUMN public."OAIRunResult"."responseDate" IS 'the responseDate from the OAI response, generated by remote server';
COMMENT ON COLUMN public."OAIRunResult"."resumptionToken" IS 'the resumption token in case there is any';
COMMENT ON COLUMN public."OAIRunResult"."resumptionTokenExpirationDate" IS 'the resumption token''s optional expiration date';
COMMENT ON COLUMN public."OAIRunResult"."nextFromTimestamp" IS 'the value of the _from_ parameter to be used in the next GET request not containing a resumptionToken.';


-- Table: public."OAIHeader"

-- DROP TABLE public."OAIHeader";

CREATE TABLE IF NOT EXISTS public."OAIHeader"
(
  "recordIdentifier" character varying(256) NOT NULL, -- the record identifier of a document
  datestamp timestamp with time zone NOT NULL, -- last modification of the document
  "setSpec" character varying(256)[], -- the sets this record belongs to
  "statusIsDeleted" boolean, -- true if the header contains the status deleted element
  CONSTRAINT "recordIdentifier" PRIMARY KEY ("recordIdentifier")
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public."OAIHeader"
  OWNER TO "reportingDB";
COMMENT ON COLUMN public."OAIHeader"."recordIdentifier" IS 'the record identifier of a document';
COMMENT ON COLUMN public."OAIHeader".datestamp IS 'last modification of the document';
COMMENT ON COLUMN public."OAIHeader"."setSpec" IS 'the sets this record belongs to';
COMMENT ON COLUMN public."OAIHeader"."statusIsDeleted" IS 'true if the header contains the status deleted element';