CONTROLLER = ENV.fetch('CONTROLLER', 'IDE Controller')

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.box_version = "9.3.0"
  config.vm.hostname = 'ReportingpDB'
  config.vm.network :forwarded_port, guest:8080, host:4724
  config.vm.network :forwarded_port, guest:5432, host:4725
  config.vm.network "private_network", ip: "192.168.42.21"
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--name", "ReportingpDB"]      
    vb.customize ["modifyvm", :id, "--cpus", "2"]     
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/playbook.yml"
  end
end
