CONTROLLER = ENV.fetch('CONTROLLER', 'IDE Controller')

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.box_version = "9.3.0"
  config.vm.hostname = 'ReportingDB'
  config.vm.network :forwarded_port, guest:8080, host:4724
  config.vm.network :forwarded_port, guest:5432, host:4725
  config.vm.network "private_network", ip: "192.168.42.22"
  
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      #echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--name", "ReportingDB"]      
    vb.customize ["modifyvm", :id, "--cpus", "2"]     
  end
end
